basePath: /
definitions:
  rest.CreatePasteRequest:
    properties:
      content:
        example: Your content
        minLength: 5
        type: string
      duration:
        example: 3
        minimum: 1
        type: integer
      paste_id:
        example: optional
        minLength: 5
        type: string
      title:
        example: Title
        minLength: 5
        type: string
    required:
    - content
    - title
    type: object
  rest.CreateShortURLRequest:
    properties:
      custom_url:
        example: shorturl
        minLength: 5
        type: string
      duration:
        example: 3
        minimum: 1
        type: integer
      original_url:
        example: https://www.google.com/
        type: string
    required:
    - original_url
    type: object
  rest.ErrorResponse:
    properties:
      error:
        type: string
      request_id:
        type: string
    type: object
  rest.PasteResponseSuccess:
    properties:
      data:
        $ref: '#/definitions/rest.createPasteResponse'
    type: object
  rest.ShortURLResponseSuccess:
    properties:
      data:
        $ref: '#/definitions/rest.createShortURLResponse'
    type: object
  rest.createPasteResponse:
    properties:
      content:
        type: string
      created:
        type: string
      expires:
        type: string
      id:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  rest.createShortURLResponse:
    properties:
      expires:
        type: string
      short_url:
        type: string
      url:
        type: string
    type: object
info:
  contact:
    email: jakueenak@gmail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Short URL API
  version: "0.1"
paths:
  /{code}:
    get:
      consumes:
      - application/json
      description: |-
        Resolve a short URL or paste data.
        Note: If got undocumented short URL, it will be redirected to the original URL means it's a short URL.
      parameters:
      - description: Short URL code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.PasteResponseSuccess'
        "301":
          description: Moved Permanently
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: resolve a short URL or paste data
      tags:
      - ShortURL
  /api/v1/paste:
    post:
      consumes:
      - application/json
      description: Create a paste
      parameters:
      - description: Create Paste Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/rest.CreatePasteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.PasteResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: create a paste
      tags:
      - Paste
  /api/v1/shorten:
    post:
      consumes:
      - application/json
      description: Shorten a URL
      parameters:
      - description: Create Short URL Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/rest.CreateShortURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.ShortURLResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: shorten a URL
      tags:
      - ShortURL
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
